spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leeblog?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    mode: HTML
    cache: false
server:
  port: 8088
logging:
  level:
    root: info
    com.lx: debug
  file: log/blog-dev.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lx.leeblog.pojo
  config-location: classpath:mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
ftp:
  host: 115.29.241.166
  port: 21
  user: lixing
  password: 123456
  prefix: http://115.29.241.166/

